-   name: Pip Install Shelfzilla Deps
    pip: requirements="{{shelfzilla_base_path}}/config/production/requirements.txt"
        executable="/usr/bin/pip2"
    sudo: yes

-   name: Python Migrate 
    shell: /usr/bin/python2.7 {{shelfzilla_base_path}}/manage.py migrate install --no-initial-data --settings=shelfzilla.settings.configfile 
    sudo: yes

-   name: Python Collectstatic
    shell: /usr/bin/python2.7 {{shelfzilla_base_path}}/manage.py collectstatic --clear --noinput --settings=shelfzilla.settings.configfile
    sudo: yes
