---
-   name: Install shelfzilla RPM
    yum: pkg=shelfzilla state=installed
    sudo: yes

-   stat: path="{{shelfzilla_base_path}}/init/shelfzilla"
    register: st

-   name: Move Shelfzilla init script
    ## Use mv instead copy because Ansible use local path as src
    command: mv "{{shelfzilla_base_path}}/init/shelfzilla" "{{system_init_path}}/shelfzilla"
    sudo: yes
    when: st.stat.exists

-   name: Change Permission of init script
    file: path="{{system_init_path}}/shelfzilla"
        owner=root
        group=root
        mode=0755
    sudo: yes

-   name: Load Shelfzilla service in boot
    service: name=shelfzilla 
        pattern="{{system_init_path}}/shelfzilla"
        enabled=yes
    sudo: yes

-   stat: path="{{shelfzilla_base_path}}/init/"
    register: st

-   name: delete init directory
    file: path="{{item}}" state=absent
    with_items:
        - "{{shelfzilla_base_path}}/init/"
    sudo: yes
    when: st.stat.exists