---
-   name: Vagrant Task
    hosts: vagrant
    roles:
        - role: common
        - role: shelfzilla_base

-   name: Production Task
    hosts: production
    roles:
        - role: common
        - role: shelfzilla_base