---
-   name: Install PostgreSQL packages
    yum: pkg={{item}} state=installed
    sudo: yes
    with_items:
        - postgresql
        - postgresql-server
        - python-psycopg2
        - postgresql-contrib
        - postgresql-libs
        - postgresql-devel

-   lineinfile: "dest=/etc/sudoers  regexp='^%vagrant' state=present line='%vagrant ALL = (postgres) NOPASSWD: ALL'"
    sudo: yes
    when: local_environment


