-   name: Install Python27 packages
    yum: pkg={{item}} state=installed
    sudo: yes
    with_items:
        - python27
        - python27-tools
        - python27-devel
        - python27-libs
        - python27-setuptools

-   easy_install: name=pip executable=/usr/bin/easy_install-2.7
    sudo: yes

