-   name: clean packages
    action: shell /usr/bin/yum clean all
    sudo: yes

-   name: restart iptables
    service: name=iptables pattern=/sbin/iptables state=restarted
    sudo: yes
    when: local_environment is true
